default_tables_model:
    resource: "@DefaultTablesModelBundle/Controller/"
    type:     annotation
    prefix:   /

default_tables_core:
    resource: "@DefaultTablesCoreBundle/Controller/"
    type:     annotation
    prefix:   /

users_profile:
    resource: "@UsersProfileBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/users
    requirements:
      _locale: en|mk

users_users_core:
    resource: "@UsersUsersCoreBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
          _locale: en|mk

login_check:
    path: /login_check

logout:
    path: /logout

groups_core:
    resource: "@GroupsCoreBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
              _locale: en|mk
