users_time_line:
    resource: "@UsersTimeLineBundle/Controller/"
    type:     annotation
    prefix:   /users/timeline

users_documents:
    resource: "@UsersDocumentsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/users
    requirements:
          _locale: en|mk

users_galery:
    resource: "@UsersGaleryBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/users
    requirements:
      _locale: en|mk

users_profile:
    resource: "@UsersProfileBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/users
    requirements:
      _locale: en|mk

users_users_core:
    resource: "@UsersUsersCoreBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
          _locale: en|mk

login_check:
    path: /login_check

logout:
    path: /logout

