security:
    encoders:
        Users\ModelBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: ModelBundle:User, property: username }

    firewalls:

            secured_area:
                logout: ~
                pattern:   ^/
                anonymous: true
                form_login:
                    target_path_parameter: register
                    login_path: login
                    check_path: login_check
                    success_handler: authentication_handler


    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/admin, roles: ROLE_ADMIN }
        - { path: ^/en/users, roles: ROLE_USER }
        - { path: ^/mk/users, roles: ROLE_USER }
