<?php

namespace Users\ModelBundle\Repo;

use Doctrine\ORM\EntityRepository;

/**
 * TimeLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeLineRepository extends EntityRepository
{
    public function getTimeLinePosts($userId)
    {
        $qb = $this->getQuseryBuilder()
            ->where('t.user = :user_id')
            ->setParameter('user_id', $userId)
            ->orderBy('t.createdAt', 'DESC')
            ->getQuery();
        $timeline = $qb->getResult();
        return $timeline;
    }


    private function getQuseryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('ModelBundle:TimeLine')
            ->createQueryBuilder('t');
        return $qb;
    }
}
